# vocab
dataset_path: /home/lunet/cojh6/Documents/MSMARCO_data/cl_dataset
vocab_path: /home/lunet/cojh6/Documents/MSMARCO_data/word-vocab-small.tsv
unk_token: 0
# word2vec
embed: /home/lunet/cojh6/Documents/MSMARCO_data/glove.6B.300d.txt
embed_dim: 300

# model
n_kernels: 11
query_max_len: 20
target_max_len: 200
batch_size: 32
schedule: 15
learning_rate: 0.00005
out_kernel: 64
max_grams: 3

model_type: cknrm
model_name: CKNRM

train_type: Dataset_train
test_type: Dataset_test
need_local_feature: False
